### ISSUE TITLE
example output CSV file

### ISSUE THREAD

**Issue by dckc** [UTHSCSA-CIRD/datafinisher#3]
ref [gpc-dev 19 July][1]

[1]: http://listserv.kumc.edu/pipermail/gpc-dev/2016q3/003061.html

**Comment by dckc** [comment]
bump

**Comment by bokov** [comment]
The following command will generate example output:

`python df.py exampleinput.db`

However, you're right, I should include a ready made one so people can compare it to what they get, etc.

**Comment by bokov** [comment]
Here you go,  	02d381d
